### ISSUE TITLE
Managing to get ImGui.NET to work with viewports

### ISSUE THREAD

**Issue by bootzin** [mellinoe/ImGui.NET#139]
Hey there!
I wanted to know if there was any reason for the ImVector class being completely readonly? 

The issue I'm having is that I need to push elements into a predefined ImVector<TPtr>, but I'm seeing no way of doing this because I can't change the size nor the capacity of it, nor do I see a way of allocating more memory to it..

What I basically want to do is a push_back equivalent (something like List<TPtr>.Add) to add a TPtr to the list

In a more detailed way: I made a custom version of ImGui.NET using the docking branch of imgui. In there, there's a ImGuiPlatformIOPtr, which has a Monitors property (of type ImPtrVector\<ImGuiPlatformMonitorPtr\>, as can be seen [here](https://github.com/bootzin/ImGui.NET/blob/master/src/ImGui.NET/Generated/ImGuiPlatformIO.gen.cs)).

The problem is, ImGui does not provide any means of initializing the Monitors property, and the way it is done in the examples is by doing a "platform_io.Monitors.resize(0);" and a "platform_io.Monitors.push_back(monitor);" ([line 612](https://github.com/ocornut/imgui/blob/docking/examples/imgui_impl_sdl.cpp)) which are native functions for c++ std::vector

So when I try to access the ImGuiPlatformMonitorPtr properties, they have a 0x00 NativePtr, and throw null reference exceptions when I try to set any of its properties, and the ImVector itself has size and capacity 0, and I'm unable to change this because it is readonly.

Do you have any idea on how could I solve this? (This is for the viewport implementation, btw, docking is working just fine)

**Comment by mellinoe** [comment]
Hey @bootzin , it's great that you're trying to get the viewport feature working. At the beginning of the year I experimented with this quite a bit and had everything fully working on top of Veldrid. Nothing ever made it into the main codebase, and I'm not sure how far it has fallen out of sync with the current state of the docking branch. In any case, this was one of the problems that I solved during that work.

I pushed the state of that branch (as of January 2019) [here]() so that you can take a look and see if any of the work there helps you. I am interested in updating all of this stuff to be compatible with the current docking branch, but I don't have a lot of time to spend on it at the moment.

Here's the snippet where I construct the `ImVector<ImGuiPlatformMonitor>`:

```C#
ImGuiPlatformIOPtr platformIO = ImGui.GetPlatformIO();
Marshal.FreeHGlobal(platformIO.NativePtr->Monitors.Data);
int numMonitors = p_sdl_GetNumVideoDisplays();
IntPtr data = Marshal.AllocHGlobal(Unsafe.SizeOf<ImGuiPlatformMonitor>() * numMonitors);
platformIO.NativePtr->Monitors = new ImVector(2, 2, data);
for (int i = 0; i < numMonitors; i++)
{
    Rectangle r;
    p_sdl_GetDisplayUsableBounds_t(i, &r);
    ImGuiPlatformMonitorPtr monitor = platformIO.Monitors[i];
    monitor.DpiScale = 1f;
    monitor.MainPos = new Vector2(r.X, r.Y);
    monitor.MainSize = new Vector2(r.Width, r.Height);
    monitor.WorkPos = new Vector2(r.X, r.Y);
    monitor.WorkSize = new Vector2(r.Width, r.Height);
}
```

Note that I also needed to make some changes down in cimgui, and at this point I can't remember if those made it into mainline cimgui or if I was operating off of a fork. Some of them are discussed here: https://github.com/cimgui/cimgui/issues/71. If you hit any issues relating to the platform function pointers, that might be a good place to start looking.

**Comment by mellinoe** [comment]
In general, the `ImGuiController` and `VeldridImGuiWindow` classes in that branch should be a good source of information for how the integration should look, assuming the docking branch has not changed drastically since I wrote that.

**Comment by bootzin** [comment]
First of all, thank you so much! Wish I had found that branch earlier, would have saved me a lot of work, but I least I got to learn a lot (:

Secondly, getting this right is proving harder than I was expecting it to be. I'm constantly getting a "EngineExecutionException" or a "Heap corrupted" message when trying to use viewports, usually in different points across the code. The code for setting the monitors did work, but I had to change ImGui.NET to implement the ImVector constructor you were using.

I also couldn't manage to get the sample project to work, as it seems imgui has changed quite a lot in that branch since January.

[Here](https://github.com/bootzin/BootEngine) is my own project, if you don't mind having a look, I'd appreciate some help to see if I'm forgetting anything. I admit that I'm having a hard time dealing with so many pointer at once. [ImGuiController](https://github.com/bootzin/BootEngine/blob/master/BootEngine/BootEngine/Layers/GUI/ImGuiController.cs) is the class where I'm setting everything up, more specifically in the SetupPlatformIo method.

Anyway, would really appreciate some help there, if we can get it to work I'd be more than happy to make a working example for ImGui.NET and update the viewport branch

**Comment by mellinoe** [comment]
@bootzin One thing that looks wrong is that you aren't preserving the delegate instance that you store in the PlatformIO struct. I am doing that on these lines: https://github.com/mellinoe/ImGui.NET/blob/viewport/src/ImGui.NET.SampleProgram/ImGuiController.cs#L93-L113

You need to store the managed delegate somewhere before getting a native function pointer to it, because otherwise it can be garbage collected. This could cause the hard crashes you are seeing.

**Comment by bootzin** [comment]
I see.. I thought Marshal would already make it so it wasn't garbage collected, but it seems that was not the case (:

Nevertheless, I'm still getting those errors.. I think this is due to the fact that I'm not preserving my ViewportDataPtr struct, which is what I'm passing over to my PlatformUsedData. Not entirely sure on the best approach on this though, as the viewportData is specific to each viewport

**Comment by bootzin** [comment]
So.. As an attempt to get this right I totally reworked my implementation in order to make it more similar to your approach and to see if I could get it to work that way (I've also created a new branch for this, intuitively named 'viewport').

But now I'm getting the weirdest of the errors.. When the first callback function is called (in this case, `GetWindowPosition`, receiving a `ImGuiViewportPtr `as its argument) the viewport it receives is not the main viewport, but instead it looks like some dirty memory reading

Here is the imgui line of code which calls the callback:
`main_viewport_platform_pos = (main_viewport->Flags & ImGuiViewportFlags_Minimized) ? main_viewport->Pos : g.PlatformIO.Platform_GetWindowPos(main_viewport);`

Now, I have debugged it and made sure that main_viewport contains the data I need (The ID, position, userData are all the same of those when I call `ImGui.GetMainViewport()` or `platformIO.MainViewport`)

The weird thing is: the argument that my function receives is definitely not the mainViewport (different ID, negative dpi, negative X and Y, etc), so when I try to get the object ([code](https://github.com/bootzin/BootEngine/blob/viewport/BootEngine/BootEngine/Layers/GUI/ImGuiController.cs#L834)) from the `PlatformUserData` pointer, it fails with the most useless message: `System.ExecutionEngineException: ''`

Any idea on what could be causing this?

**Comment by bootzin** [comment]
Found out what was the problem: it seems the first argument passed to GetWindowPosition from cimgui is a pointer to a Vector2, not a viewport, the second argument is the viewport itself

Windows are now created and destroyed properly, but their content seems to be either a simple black window, or a distorted version of the imgui demo window.. 

Also, it looks like sdl2window is using the client coordinates, not the screen coordinates, so the PumpEvents() method updates the snapshot with client coordinates as well, but when we set the io.MousePosition to be the global coordinates of SDL, it behaves with a weird offset when interactinv with imgui. Do you remember making any changes related to this on Veldrid.Sdl2?

**Comment by mellinoe** [comment]
Yes, I made some changes related to Get/SetWindowPosition in cimgui. The discussion [linked above](https://github.com/cimgui/cimgui/issues/71) talks about that, and you should take a look at [this file](https://github.com/mellinoe/cimgui/blob/viewport-experimental/cimgui_extra.cpp) to see how the issues were worked around.

**Comment by bootzin** [comment]
That's not quite what I meant.. It seems like a different version of those changes were implemented into the master branch of cimgui (in which the order of the arguments is swapped - first the position vector, then the viewport pointer), but I did manage to get that working.

My issue is that it seems that the mouse position being passed to sdl2Window is not the mouse position acquired by `p_sdl_GetGlobalMouseState`, but instead, a position relative to the application's window. This probably has to do with input and event handling, but I still need to investigate some more.

Finally, for some reason it seems like the rendering for additional viewports is not working.. The window simply stays black (although if I call `_cl.ClearColorTarget` it changes its color). This leads me to believe that the viewport's drawData is not being properly generated, but I have no idea as to why, since this should be something internal to imgui

**Comment by bootzin** [comment]
Right, so I got almost everything working properly now. The problem was actually with the `RenderImDrawData()` method, because the projection matrix was being set in a way that it only worked for single viewport mode, so I had to include window position as a offset when creating the matrix [here](https://github.com/bootzin/BootEngine/blob/viewport/BootEngine/BootEngine/Layers/GUI/ImGuiController.cs#L594-L600)

The (hopefully last) problem I'm having now is when dragging two windows out of the main viewport. What happens is that only the last dragged window renders properly, and the other one gets cleared with the proper color, but behaves weirdly when it comes to rendering (and so does the main viewport).

Here is a picture to try to make it clearer:
Before dragging:
![image](https://user-images.githubusercontent.com/23266003/66939370-55739e80-f019-11e9-922d-4b25fe3a83c8.png)

After dragging Constrained resize out:
![image](https://user-images.githubusercontent.com/23266003/66939463-7f2cc580-f019-11e9-9a8b-45085a290f3a.png)

Then after dragging Demo window out:
![image](https://user-images.githubusercontent.com/23266003/66939955-7092de00-f01a-11e9-9ed9-47104ef09936.png)

The weird window rendering also moves as I move the focused window, sometimes even disappearing entirely, but the actual window itself is still in the same place, and I can interact with it, even though it is "invisible". Any idea on why this is happening?

**Comment by bootzin** [comment]
Oh gosh, finally managed to get it to work!

I got it to create and dispose a new projection matrix and resource layout everytime I render my drawData.. This may not be optimal, but it was the easy solution, and it seems it's not computationally bad either. If you have another suggestion I'd be glad to change it 

The code is more optimized in the engine I'm creating ([BootEngine](https://github.com/bootzin/BootEngine/tree/master)), but I also got it to work in the SampleProgram of ImGui.NET, so I'll submit a PR, if you don't mind. I had some troubles getting it to work with XNA though, but it shouldn't be too hard either..

Anyway, thanks for all your help!
